### ISSUE TITLE
Racc warnings when using Rails and aarch64 together

### ISSUE THREAD

**Issue by AlanFoster** [tenderlove/aarch64#398]
Thanks for the gem! I'm hitting console warnings when attempting to use this Gem with a rails app and requiring the `aarch64/parser`, the warning is:

```
warning: already initialized constant Racc::Parser::Racc_Runtime_Version
```

Replication steps:

```
$ rails new test_aarch64
$ cd test_aarch64
$ echo 'gem "aarch64"' >> Gemfile
$ bundle
$ bundle exec rails console      
Loading development environment (Rails 7.0.8)
3.0.5 :001 > require 'aarch64/parser'
racc/parser.rb:188: warning: already initialized constant Racc::Parser::Racc_Runtime_Version
/Users/user/.rvm/gems/ruby-3.0.5/gems/racc-1.7.3/lib/racc/parser.rb:190: warning: previous definition of Racc_Runtime_Version was here
racc/parser.rb:189: warning: already initialized constant Racc::Parser::Racc_Runtime_Core_Version_R
/Users/user/.rvm/gems/ruby-3.0.5/gems/racc-1.7.3/lib/racc/parser.rb:191: warning: previous definition of Racc_Runtime_Core_Version_R was here
racc/parser.rb:207: warning: already initialized constant Racc::Parser::Racc_Main_Parsing_Routine
/Users/user/.rvm/gems/ruby-3.0.5/gems/racc-1.7.3/lib/racc/parser.rb:209: warning: previous definition of Racc_Main_Parsing_Routine was here
racc/parser.rb:208: warning: already initialized constant Racc::Parser::Racc_YY_Parse_Method
/Users/user/.rvm/gems/ruby-3.0.5/gems/racc-1.7.3/lib/racc/parser.rb:210: warning: previous definition of Racc_YY_Parse_Method was here
racc/parser.rb:209: warning: already initialized constant Racc::Parser::Racc_Runtime_Core_Version
/Users/user/.rvm/gems/ruby-3.0.5/gems/racc-1.7.3/lib/racc/parser.rb:211: warning: previous definition of Racc_Runtime_Core_Version was here
racc/parser.rb:210: warning: already initialized constant Racc::Parser::Racc_Runtime_Type
/Users/user/.rvm/gems/ruby-3.0.5/gems/racc-1.7.3/lib/racc/parser.rb:212: warning: previous definition of Racc_Runtime_Type was here
 => true 
```

I believe the warnings are being generated by:

https://github.com/tenderlove/aarch64/blob/941446b390fa3c5411e570b100411e46d9f44cda/lib/aarch64/parser.tab.rb#L190-L199

I verified in a fresh docker container to rule out local env issues and it replicates:

```
$ docker run -it ruby:3.1 /bin/bash
```

**Comment by tenderlove** [comment]
Ah, I see. That file is generated by `racc`, so I guess we'll have to fix the parser generator.  For now, I can patch this locally.

I know it would be a ton of work, but I've also considered just writing a recursive descent parser and eliminating racc.  I initially wrote the parser with racc because I thought I could finish the project faster that way.

**Comment by AlanFoster** [comment]
I took a deeper look into this; and I'm happy to try and contribute a fix. I was wondering what option you'd prefer:

- Send a pull request to racc to allow namespacing the embedded constants to stop clashes in some way; which might take a long time to eventually get shipped and a second PR to bump versions to remove the warnings from in this gem
- Remove the `racc -E` [here](https://github.com/tenderlove/aarch64/blob/0dfd9e61bf933c7b2061036fb9713bb35deb40c8/Rakefile#L165) in some capacity and have a gemspec dependency on racc (I believe that pattern is viable, but I haven't tested it)
-  Perform an additional step in the aarch64 gem after `sh "gel exec racc -E -v #{t.source}"` executes to patch up any issues 

Or any other option that works best for yourself would work for me :+1:

**Comment by AlanFoster** [comment]
Just created a new pull request for the second option of removing the `-E` option 🤞 

https://github.com/tenderlove/aarch64/pull/403
